# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
ActiveRecord::Base.transaction do
  u1 = User.create!(username: 'ctimpone')
  u2 = User.create!(username: 'agremmo')
  u3 = User.create!(username: 'jtamboer')
  u4 = User.create!(username: 'cjiang')

  p1 = Poll.create!(title: 'Poll 1', author: u1)
  p2 = Poll.create!(title: 'Poll 2', author: u2)
  p3 = Poll.create!(title: 'Poll 3', author: u3)
  p4 = Poll.create!(title: 'Poll 4', author: u4)

  q1 = Question.create!(body: 'Q1', poll_id: p1.id)
  q2 = Question.create!(body: 'Q2', poll_id: p2.id)
  q3a = Question.create!(body: 'Q3a', poll_id: p3.id)
  q3b = Question.create!(body: 'Q3b', poll_id: p3.id)
  q4a = Question.create!(body: 'Q4a', poll_id: p4.id)
  q4b = Question.create!(body: 'Q4b', poll_id: p4.id)
  q4c = Question.create!(body: 'Q4c', poll_id: p4.id)

  a1a = AnswerChoice.create!(answer: 'a', question_id: q1.id)
  a1b = AnswerChoice.create!(answer: 'b', question_id: q1.id)
  a1c = AnswerChoice.create!(answer: 'c', question_id: q1.id)
  a1d = AnswerChoice.create!(answer: 'd', question_id: q1.id)
  a2a = AnswerChoice.create!(answer: 'a', question_id: q2.id)
  a2b = AnswerChoice.create!(answer: 'b', question_id: q2.id)
  a2c = AnswerChoice.create!(answer: 'c', question_id: q2.id)
  a2d = AnswerChoice.create!(answer: 'd', question_id: q2.id)
  a3aa = AnswerChoice.create!(answer: 'a', question_id: q3a.id)
  a3ab = AnswerChoice.create!(answer: 'b', question_id: q3a.id)
  a3ba = AnswerChoice.create!(answer: 'a', question_id: q3b.id)
  a3bb = AnswerChoice.create!(answer: 'b', question_id: q3b.id)
  a4aa = AnswerChoice.create!(answer: 'a', question_id: q4a.id)
  a4ab = AnswerChoice.create!(answer: 'b', question_id: q4a.id)
  a4ba = AnswerChoice.create!(answer: 'a', question_id: q4b.id)
  a4bb = AnswerChoice.create!(answer: 'b', question_id: q4b.id)
  a4ca = AnswerChoice.create!(answer: 'a', question_id: q4c.id)
  a4cb = AnswerChoice.create!(answer: 'b', question_id: q4c.id)

  Response.create!(user_id: u1.id, answer_choice_id: a2c.id)
  Response.create!(user_id: u1.id, answer_choice_id: a3ab.id)
  Response.create!(user_id: u1.id, answer_choice_id: a3ba.id)
  Response.create!(user_id: u1.id, answer_choice_id: a4ab.id)
  Response.create!(user_id: u1.id, answer_choice_id: a4bb.id)
  Response.create!(user_id: u1.id, answer_choice_id: a4cb.id)
  Response.create!(user_id: u2.id, answer_choice_id: a1d.id)
  Response.create!(user_id: u2.id, answer_choice_id: a3ab.id)
  Response.create!(user_id: u2.id, answer_choice_id: a3ba.id)
  Response.create!(user_id: u2.id, answer_choice_id: a4ab.id)
  Response.create!(user_id: u2.id, answer_choice_id: a4bb.id)
  Response.create!(user_id: u2.id, answer_choice_id: a4cb.id)
  Response.create!(user_id: u3.id, answer_choice_id: a1b.id)
  Response.create!(user_id: u3.id, answer_choice_id: a2a.id)
  Response.create!(user_id: u3.id, answer_choice_id: a4aa.id)
  Response.create!(user_id: u3.id, answer_choice_id: a4ba.id)
  Response.create!(user_id: u3.id, answer_choice_id: a4ca.id)
  Response.create!(user_id: u4.id, answer_choice_id: a1d.id)
  Response.create!(user_id: u4.id, answer_choice_id: a2d.id)
  Response.create!(user_id: u4.id, answer_choice_id: a3ab.id)
  Response.create!(user_id: u4.id, answer_choice_id: a3ba.id)
end
